### ISSUE TITLE
Bluetooth should be forcefully running.

### ISSUE THREAD

**Issue by bhushanb010** [nic-delhi/AarogyaSetu_Android#104]
User can switch off bluetooth in public places then there might be impact on app working and then main purpose will be defeated.

**Comment by AmiyKumar** [comment]
It is unethical.

**Comment by sagar-18** [comment]
foolish suggestion

**Comment by jash-maester** [comment]
Battery life will degrade substantially too.

**Comment by bhushanb010** [comment]
It can unethical to forcefully running it. and other disadvantages though.
