### ISSUE TITLE
[Performance] Avoid using findViewById 

### ISSUE THREAD

**Issue by prudhvir3ddy** [nic-delhi/AarogyaSetu_Android#124]
start using viewbinding..

more details here https://developer.android.com/topic/libraries/view-binding

**Comment by Harin-Kaklotar** [comment]
there are no clear documentation that says use of findViewById is affect performance.

**Comment by prudhvir3ddy** [comment]
@Harin-Kaklotar before downvoting an issue, you should at least learn about it. 

if you don't know where to learn you should ask issue's author like this "where can i find more about this ?"

learn how to operate in open-source.. 

Thanks.

**Comment by Harin-Kaklotar** [comment]
https://proandroiddev.com/new-in-android-viewbindings-the-difference-from-databinding-library-bef5945baf5e

**Comment by prudhvir3ddy** [comment]
@Harin-Kaklotar 

when i am talking about removing findViewById you said findViewById doesn't affect performance.

now you are sending me link for 

viewBinding vs dataBinding 😕. 

check how dataBinding got introduced in to android then viewBinding will makes sense. 

if you are a moderator to this project you can close this issue.  i am not spending any more time arguing about this.

**Comment by Harin-Kaklotar** [comment]
oh sorry my bad.

**Comment by sagarmahobia** [comment]
@prudhvir3ddy Take a look at [this pull request](https://github.com/nic-delhi/AarogyaSetu_Android/pull/144). I've just used data binding in one activity. I know it's not perfect right now but we can enhance this further with observers. Thank you. Just asking for your feedback. :)

**Comment by prudhvir3ddy** [comment]
@sagarmahobia i am not seeing any moderators to this project nor following any practices for contribution... 

i am thinking this repo is for just finding security loopholes and mailing them.. 

so closed my issue
