### ISSUE TITLE
Force the app to run in background.

### ISSUE THREAD

**Issue by sajalkmr** [nic-delhi/AarogyaSetu_Android#128]
It should be forced to run in the background, even after removing from recent apps. Removing the app from recent menu or just clearing the ram, stops the app's functioning. It hinders it's only purpose. It won't be able to show important notifications which others have recommended to be added.

**Comment by dakshhmehta** [comment]
Even the background process gets closed that scans the nearby location?

**Comment by 1nolySk** [comment]
@sajalkumar18 It depends on smartphones, some smartphone implement killing an app from recent menu works as force stop. In stock android that's not the case, removing an app from recent apps does not kill background Services ,WorkManagers or Receivers functionality.

Only if the user manually does a **Force stop**, the app and all its background Services would stop working. This gives the user ability to control an App. So, i think its upto the user to remain updated with this app or not.
