### ISSUE TITLE
UI issue:- Text overflow issue in Helpline button. Inherited from [https://github.com/nic-delhi/AarogyaSetu_Android/issues/126](126)

### ISSUE THREAD

**Issue by ayushashi11** [nic-delhi/AarogyaSetu_Android#135]
(This issue inherits from  [https://github.com/nic-delhi/AarogyaSetu_Android/issues/126](126))
Probably setting android::ellipsize="end" and android::singleLine="true" in the button properties might work.

**Comment by aravindvnair99** [comment]
@ayushashi11 Please check for existing issues before opening a new one. You can close this and proceed there. Duplicate of #7
