### ISSUE TITLE
App crashed:- When clicks on back button after clearing chat 

### ISSUE THREAD

**Issue by ArjitRout** [nic-delhi/AarogyaSetu_Android#143]
Scenario:- App crashed:- When clicks on back button after clearing chat 
![98661A9B-937D-4D98-A2F4-D94A6CF7BF96_1_105_c](https://user-images.githubusercontent.com/37146364/82987579-60fa5f80-a015-11ea-9325-0ca3e5028474.jpeg)

Steps to reproduce:-
1. Click on  "Access Again" in hompage
2. Provide the information in chat accordingly
3. Clear chat clicking on FAB button 
4. Click on tooltip and close the tooltip
5. Click on Back button in mobile will close the app
6. Then open the app again 

Actual:- App crashed

**Comment by skccccc** [comment]
You should not display URL's on network failure. You can hide such webview based errors by display static web page on getting any webpage access error:

`web.setWebViewClient(new WebViewClient() {
@Override
public void onReceivedError(WebView view, int errorCode, String description, String failingUrl) {
               web.loadData("<html><head><style>body{background:#022D48;width:100%;height:100%;}</style></head><body></body></html>", "text/html", null);

            }
}`

Also you can minimize the app on pressing back button..

`@Override
    public boolean onKeyDown(int keyCode, @NonNull KeyEvent event) {
        if (event.getAction() == KeyEvent.ACTION_DOWN) {
            switch (keyCode) {
                case KeyEvent.KEYCODE_BACK:
                    if (web.canGoBack()) {
                        web.goBack();
                    } else {
                        moveTaskToBack(true);
                    }
                    return true;
            }
        }
        return super.onKeyDown(keyCode, event);
    }
`

**Comment by aravindvnair99** [comment]
@ArjitRout Please check for existing issues before opening a new one. You can close this and proceed there. Duplicate of #7

**Comment by ArjitRout** [comment]
@aravindvnair99 This issue is about crashing of app, #7 created for back button only. Later someone commented about crashing after i created a bug. You can check the timeline also. Just explaining my point.

**Comment by aravindvnair99** [comment]
> @aravindvnair99 This issue is about crashing of app, #7 created for back button only. Later someone commented about crashing after i created a bug. You can check the timeline also. Just explaining my point.

@ArjitRout Right, it's related though. All this is due to not handling the back action properly. So the issue is still the same. Anyways, could you upload a screen recording for replicating the issue? I'm unable to reproduce the issue.

**Comment by ArjitRout** [comment]
@aravindvnair99 Thanks for understanding the issue. I will try again to replicate and record it.

**Comment by ArjitRout** [comment]
Closing this ticket as of now, because not able to replicate after fix given for the back button issue.
