### ISSUE TITLE
Any way to disable the keystore.Properties check, or bypass it?

### ISSUE THREAD

**Issue by Lav-Hinsu** [nic-delhi/AarogyaSetu_Android#16]
Since unless you implement the server yourself, which you can't (yet), there's virtually no way to compile the app. even if you somehow add all the properties, you'll have to manually "disable" each crash or bad api response.

basically, is it possible to compile a demo version of the app, without actual api calls (since no server side code has been released (yet) ).
even a fake api inbuilt into the app would work, because implementing the server by yourself is a tough thing to do

**Comment by Lav-Hinsu** [comment]
ffs even if you comment out the keystore.properties in the build.gradle, you still can't compile it because you'll need to disable all the api calls or write a fake one.

**Comment by ashmeh6** [comment]
By adding keystore.properties file as mentioned in Readme file, i am able to build and run application(SplashScreen Activity) in emulator.

**Comment by Lav-Hinsu** [comment]
Closed, Got no response.
