### ISSUE TITLE
Slight Correction in a word (Strings-Telugu)

### ISSUE THREAD

**Issue by techy55** [nic-delhi/AarogyaSetu_Android#163]
వ్యక్తుల is the correct word in PR #140

_Originally posted by @krishnarama in https://github.com/nic-delhi/AarogyaSetu_Android/pull/140_

**Comment by adityaruplaha** [comment]
Issues are related to unmerged PRs should be commented on the PR itself so as not to spam the issue tracker.

Requesting to close.

**Comment by techy55** [comment]
That was by mistake...Sorry Guys.

--CLOSED--
