### ISSUE TITLE
Use Aadhaar card scanning as login info [Not an issue]

### ISSUE THREAD

**Issue by Gourav-Saxena** [nic-delhi/AarogyaSetu_Android#169]
Hi There,

I think, people are not giving the correct info while logging in. I advice to scan Aadhaar card and this info will always be correct. 
Or else, some how the registered mobile no should get info from Aadhaar server(using an API). 

One more idea can be here is that our testing kits should have hardware inbuilt and we may buy them from medical shops to test. This kit should only be activated only by app by scanning Aadhaar card. So if someone tests +ve then we have the correct info and officials can track them easily.

-Thanks

**Comment by chirag-jn** [comment]
The only thing which isn't available with Aadhaar is our location history (not at a granular level), and you are suggesting to expose that too?

**Comment by Gourav-Saxena** [comment]
@chirag-jn , I am suggesting to use Aadhar to get info instead of user entering that. Regarding the location, anyways if your phone's location is on then only you could be trackable.

**Comment by HaneetGH** [comment]
Aadhaar actually tells which citizen is using which device and where he is and more info from device..

that can be scary

**Comment by pikvik** [comment]
Mapping citizen adhaar is te biggest blunder any one wish to , I wonder why that to be even considered

**Comment by SarangKulkarni** [comment]
Since Aadhar is "optional", as argued in the Supreme Court case,  using it as a login instrument will prevent people without Aadhar from gaining access to the ability to protect themselves. Since it is in public interest that Aarogya Setu be inclusive and be widely adopted, Aadhar should not be used for anything related to Aarogya Setu.

**Comment by Gourav-Saxena** [comment]
I think better to close this.
-Thanks
