### ISSUE TITLE
[Request] [Feature] Improving battery life through Accelerometer.

### ISSUE THREAD

**Issue by jash-maester** [nic-delhi/AarogyaSetu_Android#181]
Almost all modern smartphones have an Accelerometer in them while the phone is set to idle for more than say 10min, 

1.  let the Aarogya Setu app daemon go into sleep, to conserver battery power.
2. But, the daemon only wakes up if it detects any rapid change from the accelerometer or GPS
3. And then starts doing its business.

**Comment by adityaruplaha** [comment]
What if people around you move about? Contact tracing needs to work in all cases. Even if you sitting still, people can pass near you, possibly causing infection. They also need to be traced.

**Comment by jash-maester** [comment]
That data can be fetched from internet(If an active internet connection is available) I mean nowadays most people using smartphones are on unlimited plans and are always connected. I am sure servers can handle such load. If an infected person is in an area... The server can send push notifications to nearby devices in that area. irrespective of BLE. 90% of people keep an active internet connection rather than Bluetooth turned ON. Hope this justifies the statement.

**Comment by adityaruplaha** [comment]
> That data can be fetched from internet(If an active internet connection is available) I mean nowadays most people using smartphones are on unlimited plans and are always connected. I am sure servers can handle such load. If an infected person is in an area... The server can send push notifications to nearby devices in that area. irrespective of BLE. 90% of people keep an active internet connection rather than Bluetooth turned ON. Hope this justifies the statement.

Well that is true for urban environments, but not so much for rural ones. Also if you're proposing contact tracing occur over the Internet, I would say that is very dangerous as attackers can intercept internet more easily than BluetoothLE (which is limited in range). This has a lot of privacy concerns, and is unrelated to the accelerometer issue anyways.

**Comment by pikvik** [comment]
considering worst case scenario and keep  BluetoothLE (which is limited in range).Moreover wit internet data tere would be lot of user data inrequired as well as senstivi can be caught

**Comment by adityaruplaha** [comment]
Well I don't see this issue being any useful as given the current codebase, accelarometer use will do more harm than good. Requesting to close.
