### ISSUE TITLE
After viewing the App I found the website is visible from where data is being loaded-

### ISSUE THREAD

**Issue by skazaadrobo** [nic-delhi/AarogyaSetu_Android#197]
Try to hide this site from the App so that anyone can't find this.
- https://web.swaraksha.gov.in/ncv19/?locale=en

**Comment by jagdishjadeja** [comment]
so its just android wrapper around webview ?

**Comment by skazaadrobo** [comment]
Yes, I think so

**Comment by pikvik** [comment]
Yes its just an android wrapper over webview

**Comment by tachyons** [comment]
What is the point of hiding that link ?

**Comment by SarangKulkarni** [comment]
It's an open-source app now, does not make sense to obfuscate link in the app and have the source be open!

**Comment by axv42** [comment]
It's pointless and impossible to hide it, you can just packet capture to see the domain.

**Comment by skazaadrobo** [comment]
I mean instead of finding bugs in App need to find bug in Website, 
And sending post request is easy in website than Android Apps

**Comment by amit27592** [comment]
The UI is not the purpose of the app here. It's location tracing, which is in the native codebase. Just the UI is being rendered via the URL, I guess to facilitate dynamic UI changes/updates.

**Comment by aravindvnair99** [comment]
@skazaadrobo This isn't an issue. Please close it. It's just a webview integrated for dynamic updates as others have pointed out. There's no reason to hide or obfuscate it.
