### ISSUE TITLE
Can we add recovery, death percentage as new feature

### ISSUE THREAD

**Issue by bharatjyoti** [nic-delhi/AarogyaSetu_Android#20]
Hi,

Thanks all for the nice app. Would like to contribute to the community. 
It would be nice if we can show daily trends of death, recovery or new cases in % wise. 

1. Does any API available for that?

**Comment by Electron-2002** [comment]
I guess unnecessary issues must not be opened. 
@bharatjyoti This isn't StackOverflow that you're enhancing our knowledge about APIs.

**Comment by bharatjyoti** [comment]
@Electron-2002 thnks for your reply and decency.... I am not enhancing your knowledge. I am enthusiastic about this product like you. Suggested my opinion.  Have some decency please. I am sure you are not the owner of the product. I am also an Developer with 10+ yrs. Thanks...don't reply

**Comment by frdaas20** [comment]
It's critical to first look for security bugs instead of feature enhancements.

Also you can checkout : http://covid19india.org : their code is open-sourced[https://github.com/covid19india/covid19india-react] too. So you can surely add more features there. Good luck.
