### ISSUE TITLE
Where can i find google json file

### ISSUE THREAD

**Issue by divyank00** [nic-delhi/AarogyaSetu_Android#215]

**Comment by DevenRathod2** [comment]
### they didn't provide the google-services.json file you need to implement this file follow this step :

1. open firebase console 
2. create a new project
3. get google-services.json file 
4. put the file on /app folder on the project

**Comment by divyank00** [comment]
And I added the keystore file, still its showing missing

**Comment by divyank00** [comment]
the debug signin sha1 key, from where should i extract?

**Comment by divyank00** [comment]
whats the host url

**Comment by crowded-geek** [comment]
Please don't use GitHub Issues for asking questions @divyank00
