### ISSUE TITLE
Use of Labels to Track Issues

### ISSUE THREAD

**Issue by sacredvoid** [nic-delhi/AarogyaSetu_Android#229]
This is not an issue, just a suggestion (more so, standard) on how to track so many issues. Use labels like 'bug', 'question', 'feature-request' etc. You can have a look at this for example. 
https://github.com/google/shaka-player/issues

Another thing, make a template for filing an issue, requesting all the logs, versions, devices for easy debugging.

Cheers!

**Comment by ayush06feb** [comment]
I think that too. The issue tracker is kind of looking messy right now. There are even many duplicate open issues and many are closely linked together but still exist individually.
The addition of tags would make life easier and closing irreverent issues (that is, without complete information or off-topic) would make the issue tracker more organized. The availability of a standard template would also make debugging easier and would allow better (saner?) readability.
All in all, it would help the developers and the contributors to easily locate and fix issues.
