### ISSUE TITLE
Can someone help in setting up this project in my IDE PLEASE

### ISSUE THREAD

**Issue by divyank00** [nic-delhi/AarogyaSetu_Android#243]
I have been trying to do it for so long but no success. I will close this issue once someone helps me, so please dont comment "No questions in issue"

**Comment by saksham1211** [comment]
What exact issue are you facing while setting up this project?

**Comment by divyank00** [comment]
I haved cloned it, have set up a firebase projess and added the json in debug and app folder, and created the keystore.properties and pasted the gote from readme. All the keys there  are empty though, like ssl_public_key,ssl_backup_key, keystore_password like everything. And it runs but it crashes saying the api endpoint is null, that is the first api which is called is null @saksham1211

**Comment by HaneetGH** [comment]
sure

**Comment by HaneetGH** [comment]
haneetatskyp ping me on skype

**Comment by divyank00** [comment]
It seems its invalid is it haneetatskyp @HaneetGH

**Comment by HaneetGH** [comment]
> It seems its invalid is it haneetatskyp @HaneetGH

No
