### ISSUE TITLE
[IMPORTANT] Submit OTP

### ISSUE THREAD

**Issue by mr-ghost3** [nic-delhi/AarogyaSetu_Android#248]
At the time of submit otp message, i thing you should put validation on it for attempt otp 3 or 4 times. Otherwise it's may be possible to brute force atteck and  it allows register with that mobile number.

**Comment by sreejeet** [comment]
Interesting.
How did you determine there is no attempt limit?
How many times did you try with an incorrect input?
Does it accept the correct OTP after many incorrect inputs?

**Comment by anivar** [comment]
points the need of #1

**Comment by kishansoni1999** [comment]
@sreejeet i was tested soo many times and yes it is accepting original otp after so many attempt fix it as soon as possible

**Comment by mr-ghost3** [comment]
Solved
