### ISSUE TITLE
Edit text Full name issue

### ISSUE THREAD

**Issue by JayMoliya33** [nic-delhi/AarogyaSetu_Android#270]
Full name field does not contain any special character like €,*,%,# etc..

Use regex and also Add toast message if user try to add special char in full name field.

**Comment by sreejeet** [comment]
How is this issue different from #274 ?

**Comment by JayMoliya33** [comment]
No both are same.

**Comment by sreejeet** [comment]
Then why did you raise duplicate issues?

**Comment by JayMoliya33** [comment]
> Then why did you raise duplicate issues?

no at first time i founded only one issue, that is Full name text field issue. after some time other Age field issue was found. so for that i created another issue.

**Comment by JayMoliya33** [comment]
can I delete this duplicate issue?

**Comment by sreejeet** [comment]
If you find more details about an existing issue, just add in a new comment under the same.

Yes please close this issue.

**Comment by JayMoliya33** [comment]
ok
