### ISSUE TITLE
Radius area info text scrolling out of box

### ISSUE THREAD

**Issue by kunjeshn** [nic-delhi/AarogyaSetu_Android#273]
The section **'In your area now, within radius of..'** The text scrolling in the box stops at improper positions and the text is not readable..

**Comment by aravindvnair99** [comment]
@kunjeshn Please check for existing issues before opening a new one. Duplicate of #246

**Comment by aravindvnair99** [comment]
@kunjeshn Please check for existing issues before opening a new one. You can close this and proceed there. Duplicate of #246

**Comment by aravindvnair99** [comment]
@kunjeshn Please check for existing issues before opening a new one. You can close this and proceed there. Duplicate of #31
