### ISSUE TITLE
[BUG]! Issue in Radius Feature (cases near me)

### ISSUE THREAD

**Issue by ranjitmnair** [nic-delhi/AarogyaSetu_Android#275]
The radius feature(cases within proximity) does not load immediately on start of the application.
It only loads after relaunching the application.
```great work indeed``` for open-sourcing the app

**Comment by aravindvnair99** [comment]
@ranjitmnair What exactly is the issue? Could you provide steps to reproduce the issue?

**Comment by ranjitmnair** [comment]
> @ranjitmnair What exactly is the issue? Could you provide steps to reproduce the issue?

It works now, it was an issue back then!
