### ISSUE TITLE
Use of sim card for tracking

### ISSUE THREAD

**Issue by sourabhvarshney111** [nic-delhi/AarogyaSetu_Android#285]
Can we use sim card for tracking purpose instead of gps and bluetooth? This way we can cover more aspects like people with normal phones.

**Comment by aravindvnair99** [comment]
@sourabhvarshney111 Cellular based tracking is not reliable (won't work in the first place) at all as compared to the GPS + Bluetooth approach. Please read more about the topic before opening an issue tracker. I would suggest closing this issue.

**Comment by ChethanH** [comment]
@sourabhvarshney111 GPS has more accurate then cellular base tracking. And you mentioned normal phone by this I assume normal phone means you trying to tell about basic phone, if my assumption is right. Then this app will not support for basic phones. Please think twice before raise the issue.

**Comment by sourabhvarshney111** [comment]
Hello @ChethanH @aravindvnair99 I am sorry I didn't clarify. I have done my research and thought not only regarding the app but the system as a whole. I know the issue regarding the range of sim card. But, as a system we are not reaching the whole of the public for which it is intended to. So, I am saying for those phones who don't have Aarogya Setu or are basic keypad phones, we can use the sim tracking way to track the containment. I know the limitations of the current approach and was thinking about a plan to overcome that. I hope you all understand my point now.

**Comment by VivekYadav7272** [comment]
Basic phones come with their own limitations, like lack of proper SDK, small memory and most importantly lack of multitasking, making a contact tracing apps that require running in the background infeasible.

**Comment by aravindvnair99** [comment]
> Hello @ChethanH @aravindvnair99 I am sorry I didn't clarify. I have done my research and thought not only regarding the app but the system as a whole. I know the issue regarding the range of sim card. But, as a system we are not reaching the whole of the public for which it is intended to. So, I am saying for those phones who don't have Aarogya Setu or are basic keypad phones, we can use the sim tracking way to track the containment. I know the limitations of the current approach and was thinking about a plan to overcome that. I hope you all understand my point now.

@sourabhvarshney111 Yes, I did get your point the first time itself. It would have certainly been a great idea if it was possible. Because that's a direct way to get everyone in the world with a cellular device to be tracked for COVID-19. We don't need people to download apps made by their governments anymore.

So, what I meant was that it's technically not possible. Yes, the technology does exist. You could do cell triangulation to identify the location of a person, but that wouldn't be accurate enough to identify where the person is and who all are around who all for how long. It's commonly used to track down criminals, but again the federal or law agencies have to resort to a manual hunt down after that approach. Because, as I said, it's only an approximate location. We could ignore this approximation, but that would lead to two situations in which people are being wrongly tagged:

1. COVID-19 infected person marked as not infected.
2. Not COVID-19 infected person marked as infected.

And that would be an even bigger risk. Because that leads to more unnecessary testing with already us having less number of test kits. And also the problem of false data injection. Criminals could also use this to make the situation worse by moving around with cell phones close to people infected.

Also, as @VivekYadav7272 the software approach isn't possible either for the very same reasons with KaiOS phones (Jio phones use KaiOS) being an exception. I spoke of the hardware approach. I hope you got my point now. If you have any thoughts or ideas or a way to come over this, I'm most welcoming and open to a discussion. Else, I would recommend closing this issue tracker.

**Comment by sourabhvarshney111** [comment]
@aravindvnair99 Sir, I have heard of a few solutions of companies delivering goods based on sim card tracking. But, for them, the sim card is dedicated for that work. If, we could discuss a way with these companies. Then, the solution is feasible.

**Comment by aravindvnair99** [comment]
> @aravindvnair99 Sir, I have heard of a few solutions of companies delivering goods based on sim card tracking. But, for them, the sim card is dedicated for that work. If, we could discuss a way with these companies. Then, the solution is feasible.

@sourabhvarshney111 Could you mention the names of the companies or any reference link that I could go through? I am sure in addition to SIM (which is if they are as normal SIM tracking is illegal), they would be using it with any other geolocating or geofencing system. I'll tell you why only SIM-based isn't possible:

![image](https://user-images.githubusercontent.com/22199259/83260437-67383980-a1d7-11ea-90c5-c57714762ea2.png)

If there is only a single tower within range of a cell phone, the accuracy is limited. You can get a direction within a sector of a certain angle and an approximate range, and that is about it.

![image](https://user-images.githubusercontent.com/22199259/83260495-86cf6200-a1d7-11ea-9858-5a00729ada5e.png)

With two towers, things get much better and you can get it narrowed down to circle a few kilometres in diameter.

![image](https://user-images.githubusercontent.com/22199259/83260550-9ea6e600-a1d7-11ea-8311-77711da3823e.png)

With three towers, which is pretty common in suburban and urban areas, the precision is more, but it's still again an area of space.

![image](https://user-images.githubusercontent.com/22199259/83260609-b7170080-a1d7-11ea-9002-a70dba60cfba.png)

And again, this is only used when requested. Normally, nobody knows where a phone is. That's how phones get stolen and aren't found (Unless we get the cops to track and also that the phone is powered on and connected to towers). Tower triangulation is a capability that only the respective ISP who controls the tower can do and they don't usually do this unless there is a court order. If there is a court order, the carrier can utilize this to find a phone. But the police can’t just call up for the heck of it and ask. They need a court order. Some other people (federal or intelligence agencies) can access this as well, but again, they need a legal reason and court approval. The idea that this is all available at the click of a mouse for “certain agencies” is television nonsense. Doesn’t happen that way at all.

In addition to all this, how large an area that a cell tower covers is dependent on the type of the user's connection. 2G > 3G > 4G > 5G. For example, 2G could cover an area of a diameter of up to 5 km, with 3G the about 2kms, and 4G about 1kms. Finally with 5G that number decreases substantially to about 200 meters. The reason being that as the frequency increases, the range decreases. That is why carriers need to install more mini cell towers than the previous generation.

Now, again there's a problem. Not everyone is on 5G and won't be anytime soon. Few countries around the world have it. But again, not on a large scale. And it doesn't exist in India. So perhaps, somewhere down the line around 10 years from now, we can successfully use cellular methods accurately. But not just now.

**Comment by sourabhvarshney111** [comment]
@aravindvnair99 Thanks for making it more clear. The companies which I were talking about were using the reference APIs from the service providers only and they have their dedicated sim cards for that. And as you mentioned, the feasibility is really scarce for the present condition of India. I will think about a more feasible approach using which we can build a contact tracing system which doesn't require the user's personal permission because in some cases, there are emergencies which are non avoidable and that should be built with the permissions of the concerned authorities.

I am closing this for now but will definitely come up with something different solution possible.

**Comment by aravindvnair99** [comment]
> @aravindvnair99 Thanks for making it more clear. The companies which I were talking about were using the reference APIs from the service providers only and they have their dedicated sim cards for that. And as you mentioned, the feasibility is really scarce for the present condition of India. I will think about a more feasible approach using which we can build a contact tracing system which doesn't require the user's personal permission because in some cases, there are emergencies which are non avoidable and that should be built with the permissions of the concerned authorities.
>
> I am closing this for now but will definitely come up with something different solution possible.

@sourabhvarshney111 Sure, tag me when you come along.
