### ISSUE TITLE
DATA SHOWING IN "WITHIN RADIUS"

### ISSUE THREAD

**Issue by akku009** [nic-delhi/AarogyaSetu_Android#286]
THE DATA AS SHOWING DIFFERENT IN SAME LOCATION WHEN WE CHECK WITH TWO PHONE

**Comment by aravindvnair99** [comment]
@akku009 Please check for existing issues before opening a new one. You can close this and proceed there. Duplicate of #31

**Comment by aravindvnair99** [comment]
@akku009 Please check for existing issues before opening a new one. You can close this and proceed there. Duplicate of #256
