### ISSUE TITLE
After opening FAQs , back button should send you on main screen

### ISSUE THREAD

**Issue by tripathi-swapnil** [nic-delhi/AarogyaSetu_Android#29]
After opening FAQs , back button should send you on main screen,

Once you hit back button of mobile, it closes your app, 

Tested in Oneplus6

**Comment by SharpSreejith** [comment]
Yes

**Comment by aravindvnair99** [comment]
@Anshdesire Please check for existing issues before opening a new one. You can close this and proceed there. Duplicate of #7

**Comment by tripathi-swapnil** [comment]
deplicate
