### ISSUE TITLE
Text flowing out of bounds from a button in homescreen when telugu language is selected

### ISSUE THREAD

**Issue by Demon-stare** [nic-delhi/AarogyaSetu_Android#293]

**Comment by sreejeet** [comment]
Are you checking before posting issues? This is your second duplicate I caught in less than 5 minutes!
This is a duplicate to issue #126

**Comment by Demon-stare** [comment]
Sorry my bad i am a newbie *facepalm*
Closing it...

**Comment by Demon-stare** [comment]
I will make sure this will never happen again...

**Comment by ramank775** [comment]
> Are you checking before posting issues? This is your second duplicate I caught in less than 5 minutes!
> This is a duplicate to issue #126 
Please be little gentle with your words!!
