### ISSUE TITLE
Inclusion of areas of Red,Orange and Green Zone.

### ISSUE THREAD

**Issue by yash982000** [nic-delhi/AarogyaSetu_Android#320]
I want to bring attention to including one feature about highlighting areas of Red, Orange, and Green Zone in the App. It would be really helpful for the user to know about his surroundings and how to expect further for any services in their areas like hospitals, transportation, food, and restaurant, travel, groceries and shop markets, etc. Someone, please guide on this and I am more than happy to work on this.

**Comment by aravindvnair99** [comment]
@yash982000 Please check for existing issues before opening a new one. You can close this and proceed there. Duplicate of #71

**Comment by yash982000** [comment]
@aravindvnair99  Okay. I tried to find but as there was no description in the title, I cannot find it. Thank you for your guidance :)
