### ISSUE TITLE
No rate limit on login page.

### ISSUE THREAD

**Issue by Onyx24** [nic-delhi/AarogyaSetu_Android#344]
Hi, there is no rate limit of otp attempts on login page which enables to brute force the 6 digit and takeover the account. Please add rate limit after 3-4 attempts.

**Comment by jaydeepw** [comment]
@delhiamitk this makes sense to avoid backend from being bogged down with frequent OTP requests.

**Comment by sreejeet** [comment]
Duplicate of #248

**Comment by Onyx24** [comment]
@sreejeet please check my other issues.

**Comment by sreejeet** [comment]
This issue was already raised at #248. What does it have to do with your other issues?

**Comment by Onyx24** [comment]
yes i am closing this. Pls check #346 and #347
