### ISSUE TITLE
Access to JS files..

### ISSUE THREAD

**Issue by Onyx24** [nic-delhi/AarogyaSetu_Android#347]
Hello, I am able to access js files which are externally forbidden.. pls let me know if should I send the details to security email or here?

**Comment by aravindvnair99** [comment]
@Onyx24 Please provide more details. What JS files are you talking about?

**Comment by Onyx24** [comment]
Hi I can provide details but it maybe related to security issue so how can I reveal here on public? Can I send it to your email if you r from setu team?

**Comment by Onyx24** [comment]
Hi @aravindvnair99 please also check #344  #346  #349

**Comment by Onyx24** [comment]
Check this. I found many more js files..

**Comment by sreejeet** [comment]
> Hello, I am able to access js files which are externally forbidden.. pls let me know if should I send the details to security email or here?

How would we know if you should send an email or not without knowing the details? I suggest you send an email directly to them if you think it is a security threat.

You may close issue this now.
