### ISSUE TITLE
Percentage calculation error

### ISSUE THREAD

**Issue by navin240** [nic-delhi/AarogyaSetu_Android#363]
The percentage of death ratio and recovery ratio is calculated wrong.

**Comment by Josephdias92** [comment]
upload screenshot please

**Comment by navin240** [comment]
![1590832719508](https://user-images.githubusercontent.com/66158193/83325511-5dbbd980-a28a-11ea-866c-c6d8c4449f4f.jpg)
![1590832777463](https://user-images.githubusercontent.com/66158193/83325535-90fe6880-a28a-11ea-945a-e7812b0a4aba.jpg)
![Uploading 1590832868185..jpg…]()

**Comment by navin240** [comment]
![1590832719508](https://user-images.githubusercontent.com/66158193/83325511-5dbbd980-a28a-11ea-866c-c6d8c4449f4f.jpg)
![1590832777463](https://user-images.githubusercontent.com/66158193/83325535-90fe6880-a28a-11ea-945a-e7812b0a4aba.jpg)
![1590832868185](https://user-images.githubusercontent.com/66158193/83325551-a5426580-a28a-11ea-9d6e-d46b7e14baa4.jpg)

**Comment by aishmittal** [comment]
The percentage of ratios calculated are correct.  
Just use this formula to calculate the percentage change: 
**Increase = New Number - Original Number**
**% increase = Increase ÷ Original Number × 100**

**Comment by navin240** [comment]
@aishmittal can you please show the above calculation of Maharashtra's recovery rate

**Comment by aishmittal** [comment]
@navin240 Here is the calculation
Increase = New Number - Original Number
8381 = 26997 - Original Number
Original Number = 26997 - 8381 = 18616
% Increase = (Increase/Orignal Number)*100 = (8381/18616)*100 = 45.02 %
