### ISSUE TITLE
Language compatibility Issues in Malayalam (UX/UI)

### ISSUE THREAD

**Issue by SharpSreejith** [nic-delhi/AarogyaSetu_Android#374]
**Tested on 6.0 inch Screen mobile. 

Aarogya setu v1.1.3**

It might be because of giving fixed size for buttons or it may be due to the current font style. 

The words are not properly aligned.

Issues found in Call helpline and Assess Again buttons in main screen, Things to do next , FAQ etc..

**Comment by SharpSreejith** [comment]
#Duplicate of #373

**Comment by sreejeet** [comment]
Please close this if it is a duplicate. Add your comments to the existing issue.
