### ISSUE TITLE
No option to decline Privacy Policy.

### ISSUE THREAD

**Issue by ycpatel813** [nic-delhi/AarogyaSetu_Android#377]
There should have an option to decline Privacy Policy or Close option.

![Privacy Policy](https://user-images.githubusercontent.com/8921044/83333937-caea6180-a2c0-11ea-9524-67092b66c50f.jpeg)

**Comment by nixphix** [comment]
In web or desktop apps declining the EULA or Privacy Policy would redirect or close the installation process, here it is "uninstall the app" which is clearly mentioned on point 5 in your screenshot.

AFAIK app stores your interaction data on the device and shares it only when your are diagnosed with COVID-19 to find others who might be infected.

Close the issue if that answers your question.

**Comment by ycpatel813** [comment]
@nixphix, Okay. Closed issue as per above comment.
