### ISSUE TITLE
screen rotation doesn't work for this application 

### ISSUE THREAD

**Issue by sweetybandgar** [nic-delhi/AarogyaSetu_Android#380]
Just downloaded the application, it is great but found out that screen rotation doesn't work of this application. Only the portrait view available. If this feature is there it will make the experience more satisfying.

**Comment by aravindvnair99** [comment]
@sweetybandgar Please check for existing issues before opening a new one. You can close this and proceed there. Duplicate of #258

**Comment by sweetybandgar** [comment]
Thank
