### ISSUE TITLE
App config file which is externally unauthorized can be seen..

### ISSUE THREAD

**Issue by Onyx24** [nic-delhi/AarogyaSetu_Android#383]
Hello,

i am able to view the data on here https://fp.swaraksha.gov.in/api/v1/app/config/
It says this error when opening this link on browser

Unauthorized
The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.

I just used my proxy intercept tool to check this and it showed me the data in response code.

Below are the request and response...

Request :- 

GET /api/v1/app/config/ HTTP/1.1
pt: 9cf23ec2-d83c-4778-aca5-d7fb64ae1b2d
ver: 1047
ver-name: 1.1.3
os: 23
device-type: samsung-SAMSUNG-SM-N910A
Content-Type: application/json
pt: 9cf23ec2-d83c-4778-aca5-d7fb64ae1b2d
ver: 1047
Host: fp.swaraksha.gov.in
Connection: close
Accept-Encoding: gzip, deflate
User-Agent: okhttp/3.14.7

Response :-

HTTP/1.1 200 OK
Date: Fri, 30 May 2020 19:22:03 GMT
Content-Type: application/json
Connection: close
Server: nginx
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST
Access-Control-Allow-Headers: Authorization, pt, ver, content-type
Content-Length: 203

{"f_upgrade_android":{"min_version":1041,"specific_version":[0]},"is_force_upgrade_required_ios":{"min_version":"0.0","specific_version":["1.5"]},"max_count_read_write":10,"max_data_persisting_days":30}

**Comment by dsarkar99** [comment]
You can’t. Because you’re not passing any credentials, are you?

**Comment by Onyx24** [comment]
> You can’t. Because you’re not passing any credentials, are you?

what do you mean?

**Comment by dsarkar99** [comment]
If you have opened the link. You have seen that it’s saying ‘unauthorized’. That means while accessing this link it will require some credentials to access. I guess config contains some details so they might have implemented authentication there. Anyway, if someone comes up with any solution then it i obviously appreciable 😅

**Comment by Onyx24** [comment]
please check this @delhiamitk #383

**Comment by dsarkar99** [comment]
Btw, why do you need that @Onyx24 ?

**Comment by aravindvnair99** [comment]
@Onyx24 This is correct. Normally, it's not accessible because you are not authorized. Hence the 401 HTTP status code. By using your phone and the proxy hookup, your phone is giving the authentication credentials which have the right authorization. I don't see any security issues here.

**Comment by Onyx24** [comment]
Alright pls check my other issues.

**Comment by Onyx24** [comment]
{"f_upgrade_android":{"min_version":1041,"specific_version":[0]},"is_force_upgrade_required_ios":{"min_version":"0.0","specific_version":["1.5"]},"max_count_read_write":10,"max_data_persisting_days":30}



What is this related to?

**Comment by aravindvnair99** [comment]
> {"f_upgrade_android":{"min_version":1041,"specific_version":[0]},"is_force_upgrade_required_ios":{"min_version":"0.0","specific_version":["1.5"]},"max_count_read_write":10,"max_data_persisting_days":30}
> 
> What is this related to?

@Onyx24 It's just some configuration metadata. Nothing vulnerable here. You can close this issue.

**Comment by Onyx24** [comment]
okay check other issues also pls
