### ISSUE TITLE
Tracking range 

### ISSUE THREAD

**Issue by mrkingmeerut** [nic-delhi/AarogyaSetu_Android#390]
Did not find using the symmetric key(PRAGMA key) to encrypt the SQLite databases.

**Comment by aravindvnair99** [comment]
@mrkingmeerut To clarify, what exactly is the issue? The stats are being displayed correctly.

**Comment by mrkingmeerut** [comment]
MITM Vulnerability

**Comment by aravindvnair99** [comment]
> MITM Vulnerability

@mrkingmeerut Please provide more details.

**Comment by mrkingmeerut** [comment]
Can you explain which type of details?
Can I talk to private like as whatsapp

**Comment by aravindvnair99** [comment]
> Can you explain which type of details? Can I talk to private like as whatsapp

@mrkingmeerut Sorry, I'm not open to WhatsApp. Please provide more details on what the issue is and where do feel a MITM attack is possible as you said. You said `Tracking in radius is not show in aarogye setu app`. Please elaborate on that.

**Comment by mrkingmeerut** [comment]
This app is not using critical function 'Runtime.getRuntime().exec("...")'.
