### ISSUE TITLE
Broken Hyperlink 

### ISSUE THREAD

**Issue by DeepakArya83** [nic-delhi/AarogyaSetu_Android#409]
After Self test perform, There is message displayed "You are advised for testing as your infection risk is high..........and so on". There is a hyperlink provided in this message to watch "List of Testing Centers: https://icmr.nic.in/node/39071 " 
This link is not available as error "404 not found" appears when we hit the link.

**Comment by sreejeet** [comment]
Please check and close if this is a duplicate of issue #12.
