### ISSUE TITLE
updated app and still the reload button on "Assess Again" is the same

### ISSUE THREAD

**Issue by ghost** [nic-delhi/AarogyaSetu_Android#422]
I have updated the app from the google play store a few mins ago and i see this reload/refresh button unchanged

Mobile : Mi note 7
Android version : 9 
Miui : 11global (stable)

**Comment by bobobarry** [comment]
@BlueTick9000 what did you tell me about this server # Server SSL Keys # configuration ?

**Comment by sreejeet** [comment]
Possible duplicate of #7. Please check and confirm.
Was it mentioned anywhere in the update that this issue will be fixed?

**Comment by bobobarry** [comment]
I think you are executed on your android studio application
