### ISSUE TITLE
Why the native framework is not adopted?

### ISSUE THREAD

**Issue by pradpant** [nic-delhi/AarogyaSetu_Android#44]
Instead of developing the App for two Platforms with two different codebases, you can have got in one codebase if you have used a framework like flutter. That would be much easier for developers to find a bug and that will be rectified with ease.

**Comment by Electron-2002** [comment]
Why is this an issue now? The app has already been created, I don't think to raise this as an issue is going to help. 

@pradpant Whatever you're saying makes sense, still this issues fragment isn't for this I guess.

**Comment by sreejeet** [comment]
This happens when you have to create applications on a VERY fast paces for emergencies. In situations like these, certain decision need to be made which may not be agreeable by all.

Yes, it could have been better, but the app needed to be release as soon as possible.
I'm sure the developers took the best decision possible.

**Comment by Lav-Hinsu** [comment]
probably because to get low level functionality like blutetooth, you'll still have to use platform channels and implement them for each platform anyways. plus native android is still far better for high level control required by apps like these.

**Comment by HaneetGH** [comment]
Developing App in Native is a good way to use full potential of android device..

I personally prefer Native Over Flutter react or any other hybrid app..

Facebook is using it but my personal preference

**Comment by arpanbag001** [comment]
> Instead of developing the App for two Platforms with two different codebases, you can have got in one codebase if you have used a framework like flutter. That would be much easier for developers to find a bug and that will be rectified with ease.

Flutter is not the silver bullet. Both native and flutter has their own strengths and weaknesses. I personally prefer native for most projects, because I can get all the features of Android.

**Comment by ch4nd4n** [comment]
> you can have got in one codebase if you have used a framework like flutter.

Did you go through the code and figure out if Flutter is best fit for this? For eg. Background location service, Bluetooth beacon etc.? Given that there is little documentation on flutter.dev on bluetooth, IDK if it would make much sense to build something where primary dependency itself is unknown.

Please make a working prototype with flutter and see how feasible it is.

**Comment by vamshi9666** [comment]
Title should be "why any cross platform framework isn't adopted? "

**Comment by navanshu** [comment]
Majorly depends on the developers and team skills. Whats they are comfortable with and that would produce the best quality of code they can. Doing something the right way and delaying launch of this application would have been a bullet into the foot of our country. Close this thread.
