### ISSUE TITLE
In Assist question activity the reset FAB icon is not visible

### ISSUE THREAD

**Issue by beingentangled** [nic-delhi/AarogyaSetu_Android#45]
To reproduce:

1.Click blue assist button from homepage
2.Check the button at the right corner without refresh icon.

**Comment by sreejeet** [comment]
#7

**Comment by sreejeet** [comment]
Duplicate of #7

**Comment by aravindvnair99** [comment]
@beingentangled Please check for existing issues before opening a new one. You can close this and proceed there. Duplicate of #7
