### ISSUE TITLE
Feature Request: Tell the location and time when the contact with covid19 patient happen to the user

### ISSUE THREAD

**Issue by lakshaykaushik** [nic-delhi/AarogyaSetu_Android#462]
In addition to the status change from safe to high risk when a user comes in contact with a covid positive patient, the app should also tell:
1. Location where contact happened. 
2. Time when contact happened.

As this is information is already being collected, this should be shared with user too.

**Comment by manan025** [comment]
I would like to work on this feature request.

**Comment by AmulPatil** [comment]
social distancing violation tracker area wise or device type : suppose if we see more devices are being interacting at particular location ,then some sort of alert saying social distancing has been gone for toss at these locations. and notify the devices which are violating most.

**Comment by lakshaykaushik** [comment]
Looks like this issue is closed as linked issue https://github.com/nic-delhi/AarogyaSetu_Android/issues/485 has been implemented. I can see in the app that location and time of contact is being reported. 

Good work folks!
