### ISSUE TITLE
Unknown route for Terms of Use in App Drawer

### ISSUE THREAD

**Issue by AbhayVAshokan** [nic-delhi/AarogyaSetu_Android#493]
On clicking the Terms of Use link on the app drawer, it gets redirected to a page displaying ```cannot GET /tnc/```, which is the error for unknown route /tnc/.

## Screenshot
<img src="https://user-images.githubusercontent.com/35297280/85965457-6105ca80-b9da-11ea-9a10-94aa76f2d70f.jpeg" width=40%>

**Comment by shahsurajk** [comment]
This seems to be working for me on the latest version v1.4.1
