### ISSUE TITLE
why the device.getAddress (MAC address) is not saved in db

### ISSUE THREAD

**Issue by 16Abhishek** [nic-delhi/AarogyaSetu_Android#523]
why the device.getAddress (MAC address) is not saved in db?
how to get correct case if both phones have same deviceName()

plz help me to clear my concept.
thank you

**Comment by divu050704** [comment]
do you tried this out??

**Comment by 16Abhishek** [comment]
After some R&D on bluetooth , got to know that MAC randomization is enabled by default for client mode from Android 8 .
So there is no use of getting MAC address to trace / detect person who is having app installed . One way to this is create a unique id and set as bluetooth name and for every near by device scan check for device.getName . Its working for my requirement.

Please correct me if my assumption is wrong .
Thanks to ArogyaSetu SourceCode
