### ISSUE TITLE
[Question] Is open-sourcing the iOS App on the roadmap?

### ISSUE THREAD

**Issue by HirdayGupta** [nic-delhi/AarogyaSetu_Android#58]
Thanks for open-sourcing the Android App! A fantastic step towards openness and transparency. I would like to ask, will the iOS App be open-sourced in a similar fashion anytime soon? It will be another great step towards openness.

Thanks.

**Comment by sreejeet** [comment]
https://static.mygov.in/rest/s3fs-public/mygov_159050700051307401.pdf

**Comment by HirdayGupta** [comment]
Thank you @sreejeet!
