### ISSUE TITLE
Pressing back button after playing a video from media exits the app

### ISSUE THREAD

**Issue by pranshu-chandra** [nic-delhi/AarogyaSetu_Android#64]
After playing any video on the Media section, pressing the back button should open the Media home page but instead exits the app.

**Comment by developergirl53** [comment]
Yes and for entire app the same flow any subsection resultant is only exit happening, back pressed need to be handled.

**Comment by namanrana16** [comment]
same problem as #42 and #29

**Comment by sreejeet** [comment]
Duplicate of #7

**Comment by aravindvnair99** [comment]
@pranshu-chandra Please check for existing issues before opening a new one. You can close this and proceed there. Duplicate of #7
