### ISSUE TITLE
Mask detection can be added

### ISSUE THREAD

**Issue by skullcandy69** [nic-delhi/AarogyaSetu_Android#67]
A feature for detecting whether or not a person is wearing a mask if going outside

**Comment by adityaruplaha** [comment]
I disagree, I would rather not have an app checking my camera whenever I go out.

**Comment by deva-gopalani** [comment]
I don't find this to be a solution. If a person is not wearing a mask, then he won't open the app at all since he knows that there is a mask detection feature. 
And as said by @adityaruplaha access of camera might raise concerns among the people and thus limit the usage.

**Comment by iSumitBanik** [comment]
> A feature for detecting whether or not a person is wearing a mask if going outside

Sorry to say but it won't serve the application's sole purpose. And, _Mask Detection_ thing should be employed on a central authority based as employee check-in/check-out or in a public gathering place. That's it

Like this which is shown below.

![image](https://user-images.githubusercontent.com/36637433/82976245-2e903880-9ffc-11ea-9a94-c3b4aa9b9725.png)

**Comment by aravindvnair99** [comment]
@skullcandy69 Please close this issue as has been clarified by @adityaruplaha, @deva-gopalani and @iSumitBanik. This issue isn't relevant.
