### ISSUE TITLE
[feature] dynamic status screen

### ISSUE THREAD

**Issue by parshnt** [nic-delhi/AarogyaSetu_Android#69]
Currently many places (i,e airports) use the Aarogya Setu app as a "pass" to allow only "safe" citizens to access the place/service. Since the status screen is rather static, There's a potential, that someone might be showing a similar-looking but forged image of the status screen.

A solution to this would be to add some kind of dynamic factor to the status page. for example, an animated color scheme that changes with factors like time, +ve cases in the locality, etc. would be difficult to forge.

I know Aarogya Setu doesn't allow screenshots, but still to be on a safe side.

**Comment by adityaruplaha** [comment]
I'm not sure if I should create a new issue for this, but I feel that a QR code based solution will work best. For securing entry, you have to scan a QR code presented at (say) the airport. This is highly contactless as no manual checks are needed. Only scan the QR, it sends the identity and location to the server, and now the server knows when and where you entered the country(/state, if implemented). 

A possible downside of this may be that someone clicks a photo of the QR and it gets scanned unnecessarily. To counter this, we can add a simple OTP system, sent to a device located at the checkpost where the code is scanned. This code (6 or 8-digits will be good enough I think) changes every 20 seconds or so. The rest of the process is similar to that of apps like Google Authenticator.

**Comment by parshnt** [comment]
Yep, totally and we need this feature more than ever now, Since the source is released now, anyone can disable backend checks after editing the code and always show himself as "safe".

**Comment by vasthava** [comment]
I guess it for the same reason they disabled screenshot feature in the recent update..Yeah i guess we ll find  a lot of mods/spoofed versions will be available in the market

**Comment by adityaruplaha** [comment]
I agree. Also we need protection against unofficial builds on the server side too.
