### ISSUE TITLE
No such file as keystore.properties

### ISSUE THREAD

**Issue by kmanishk1** [nic-delhi/AarogyaSetu_Android#78]
Build file '<rootFolder>/app/build.gradle' line: 12
A problem occurred evaluating project ':app'.
-- <rootFolder>/keystore.properties (No such file or directory)

This error occurs since there is no available Keystore signed up values available. The code and its requirement in `app/build.gradle` need to be changed.

**Comment by legendavey** [comment]
Please search among the open issues before creating duplicates. I believe #16 already covers your issue.

**Comment by kmanishk1** [comment]
Sorry, my bad. And thanks for your help.
