### ISSUE TITLE
Build fails because of missing keystore.properties

### ISSUE THREAD

**Issue by sudheesh001** [nic-delhi/AarogyaSetu_Android#9]
The gradle build of the project looks for a `keystore.properties` file, which is missing from the checked in codebase.
```
def keystorePropertiesFile = rootProject.file("keystore.properties")
def keystoreProperties = new Properties()
keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
```

While the details are mentioned in the readme, please checkin a default file as is which needs to be configured by the developers running the build.

**Comment by Chinmay-KB** [comment]
If you read the readme.MD carefully you'll see they have mentioned it to create a keystore.properties in the root directory

Modi ji should rezine XD

**Comment by sudheesh001** [comment]
> please checkin a default file as is which needs to be configured by the developers running the build.

The suggestion was this. Please take a look at the issue again.

**Comment by sudheesh001** [comment]
Closing in favor of #16 which was the right way to ask this.

**Comment by anirudh-chhangani** [comment]
having a default file sounds like a reasonable suggestion.

**Comment by Lav-Hinsu** [comment]
author of #16  here. this should've been thought out by developers before releasing the source code, because unless you fix this or implement a api (if you successfully implement one, let me know), there's actually no way to compile this.

**Comment by sudheesh001** [comment]
Thank you, I agree with this. I agree that I might have suggested this very poorly in my original issue report but this is definitely a blocker and not an unreasonable ask. Maybe provide the APIs to a mock sandbox server to begin with?

**Comment by manojnagendra** [comment]
> author of #16 here. this should've been thought out by developers before releasing the source code, because unless you fix this or implement a api (if you successfully implement one, let me know), there's actually no way to compile this.

Does commenting out the `release` build instructions fix the issue, at least for now?

**Comment by Lav-Hinsu** [comment]
> > author of #16 here. this should've been thought out by developers before releasing the source code, because unless you fix this or implement a api (if you successfully implement one, let me know), there's actually no way to compile this.
> 
> Does commenting out the `release` build instructions fix the issue, at least for now?

Nope, tried it. fails. even with a firebase.json added. probably because it was not built with a demo/fake api in mind. why even release the code if no one alive except them could compile it?

**Comment by HaneetGH** [comment]
1.create keystore.properties in project folder
2.update the content as per read.me
3.update build.gradle
4. def keystorePropertiesFile = rootProject.file("./keystore.properties")

start build 

at least code compiles

**Comment by Lav-Hinsu** [comment]
even if you do this, all the api responses will result in errors or 404s resulting in either the app crashing or You not being able to going past the login screen.
