### ISSUE TITLE
add contribution guidelines

### ISSUE THREAD

**Issue by prakashperam** [nic-delhi/AarogyaSetu_Android#99]
As it requires to set up open source contributor guidelines and issue raising guidelines and POCs should be properly mentioned.

**Comment by ashmeh6** [comment]
Each bug fixing should have their bug/feature branch .
branch format could look like below.
bug/feature-->dev_branch-->master_branch 
After proper code review bug/feature branch should be merge to dev_branch or master.

**Comment by prakashperam** [comment]
Could you include in the ReadMe file if it's not already been there
